// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCANwv5nkHwcqBleRJccBahahx0VqChBQA',
    appId: '1:565182076250:web:cefa711ab5103c42c94f63',
    messagingSenderId: '565182076250',
    projectId: 'sabueso-acc3c',
    authDomain: 'sabueso-acc3c.firebaseapp.com',
    storageBucket: 'sabueso-acc3c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzjNcGCvGvoEqC0ndkWhtwItC76J7nFK8',
    appId: '1:565182076250:android:f7ae4bae53d98efbc94f63',
    messagingSenderId: '565182076250',
    projectId: 'sabueso-acc3c',
    storageBucket: 'sabueso-acc3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiNscF4l8CNbGyD3zauDwUyI9Z_sTm8oY',
    appId: '1:565182076250:ios:6ec2ecc78cf3b8b7c94f63',
    messagingSenderId: '565182076250',
    projectId: 'sabueso-acc3c',
    storageBucket: 'sabueso-acc3c.firebasestorage.app',
    iosBundleId: 'com.example.sabueso',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiNscF4l8CNbGyD3zauDwUyI9Z_sTm8oY',
    appId: '1:565182076250:ios:6ec2ecc78cf3b8b7c94f63',
    messagingSenderId: '565182076250',
    projectId: 'sabueso-acc3c',
    storageBucket: 'sabueso-acc3c.firebasestorage.app',
    iosBundleId: 'com.example.sabueso',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCANwv5nkHwcqBleRJccBahahx0VqChBQA',
    appId: '1:565182076250:web:8850d1eb57d54280c94f63',
    messagingSenderId: '565182076250',
    projectId: 'sabueso-acc3c',
    authDomain: 'sabueso-acc3c.firebaseapp.com',
    storageBucket: 'sabueso-acc3c.firebasestorage.app',
  );
}
